version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'bookstore'
      MYSQL_USER: 'softdesign'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/tmp/mysql:/var/lib/mysql

  backend:
    container_name: backend_yii
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/vendor

    ports:
      - 8080:80
  frontend:
    container_name: frontend_angular
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 4200:4200